### ISSUE TITLE
Erro de digitação

### ISSUE THREAD

**Issue by MatheusBBarni** [Camilotk/ocaml4noobs#13]
Olá, estava seguindo os passos da primeira parte e me deparei com esse erro nessa [parte](https://github.com/Camilotk/ocaml4noobs/tree/master/1-introducao#instala%C3%A7%C3%A3o):

(https://user-images.githubusercontent.com/29718530/128101557-5537760d-015e-499c-ba69-9de5e4e46f97.png)

E o certo seria `ocaml --version`.

**Comment by Camilotk** [comment]
OCaml usa um hífen como padrão para o comando de versão:

![image](https://user-images.githubusercontent.com/30880723/128238087-01c180f2-0538-4e29-9e4f-555eef1ffff2.png)

Se você usar o comando **man** (manual) vai ter a lista de parâmetros:
```terminal
$ man ocaml
```

![image](https://user-images.githubusercontent.com/30880723/128238230-3ba147b6-8f2c-4056-b375-333aec9308df.png)

E lá vai ter **-version**:
![image](https://user-images.githubusercontent.com/30880723/128238346-b2342b84-3c68-4908-aeb8-24eed0ea9d36.png)

**Comment by MatheusBBarni** [comment]
Interessante, tinha tentando ocaml -version e tinha dado que o comando não existia, mas agora que fiz o alias com o rlwrap foi. obrigado pela resposta. Valeu!
